# Generated by Django 6.0.3 on 2026-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
